-- MySQL Script generated by MySQL Workbench
-- Sun 09 Apr 2023 04:16:20 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(25) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`));


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `profesion` VARCHAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `descripcion` LONGTEXT NOT NULL,
  `img_perfil` VARCHAR(45) NULL,
  `banner` VARCHAR(255) NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_perfil`),
  INDEX `fk_perfil_user_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(55) NOT NULL,
  `descripcion_proyecto` VARCHAR(255) NOT NULL,
  `link_url` VARCHAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `link_repo` VARCHAR(255) NOT NULL,
  `img_proyecto` VARCHAR(255) NULL,
  `perfil_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_proyecto`),
  INDEX `fk_proyecto_perfil1_idx` (`perfil_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_perfil1`
    FOREIGN KEY (`perfil_id_perfil`)
    REFERENCES `mydb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skill` (
  `id_skill` INT NOT NULL AUTO_INCREMENT,
  `nombre_skill` VARCHAR(55) NOT NULL,
  `icono_skill` VARCHAR(255) NULL,
  `perfil_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_skill`),
  INDEX `fk_skill_perfil1_idx` (`perfil_id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_skill_perfil1`
    FOREIGN KEY (`perfil_id_perfil`)
    REFERENCES `mydb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`skill_has_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skill_has_proyecto` (
  `skill_id_skill` INT NOT NULL,
  `proyecto_id_proyecto` INT NOT NULL,
  PRIMARY KEY (`skill_id_skill`, `proyecto_id_proyecto`),
  INDEX `fk_skill_has_proyecto_proyecto1_idx` (`proyecto_id_proyecto` ASC) VISIBLE,
  INDEX `fk_skill_has_proyecto_skill1_idx` (`skill_id_skill` ASC) VISIBLE,
  CONSTRAINT `fk_skill_has_proyecto_skill1`
    FOREIGN KEY (`skill_id_skill`)
    REFERENCES `mydb`.`skill` (`id_skill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_has_proyecto_proyecto1`
    FOREIGN KEY (`proyecto_id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
